# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftDemo
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa'
  pod 'RxKeyboard'
  pod 'Alamofire', '~> 4.9.1'

end
